[package]
name = "native-module"
version = "0.1.0"
authors = ["Skiro"]
edition = "2018"
publish = false

[dependencies]
tokio = { version = "1.25.0", features = [ "rt" ] }

[dependencies.rquickjs]
path = "../.."
default-features = false
features = ["exports", "loader"]
